import React from "react";
import "../../styles/Dashboard/AGB.css"

function AGB() {
    return(
        <div className="agb">
            <h1>Impressum & Datenschutz</h1>
            <div>
                <div className="containerOne">
                    <h2>Impressum</h2>
                    <p>Angaben gemäß § 5 TMG: Rene Brandt</p>
                    <p>Bottel: Das Tattoo- und Piercingcenter im Westmünsterland</p>
                    <p>Lüderitzstraße 1a, 48683 Ahaus</p>
                    <p>Kontakt: Telefon: 0152 – 531 56 569</p>
                    <p>E-Mail: bottel@gmx.de</p>
                    <p>Umsatzsteuer-Identifikationsnummer gemäß §27 a Umsatzsteuergesetz: DE219683351</p>
                    <p>Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</p>
                </div>
               <div className="containerTwo">
                <h2>Datenschutzerklärung (Stand: 5/2018)</h2>
                <p>Die nachfolgende Datenschutzerklärung gilt für die Nutzung unseres Online-Angebots https://www.tattoo-piercing-profi.de (nachfolgend „Website“).</p>
                <p>Wir messen dem Datenschutz große Bedeutung bei. Die Erhebung und Verarbeitung Ihrer personenbezogenen Daten geschieht unter Beachtung der geltenden datenschutzrechtlichen Vorschriften, insbesondere der Datenschutzgrundverordnung (DSGVO).</p>
                <h4>1. Verantwortlicher</h4>
                <p>Verantwortlicher für die Erhebung, Verarbeitung und Nutzung Ihrer personenbezogenen Daten im Sinne von Art. 4 Nr. 7 DSGVO ist:</p>
                <p>BOTTEL: Dein Tattoo & Piercingstudio in Ahaus</p>
                <p>Inh.: Rene Brandt</p>
                <p>Lüderitzstraße 1A, 48683 Ahaus</p>
                <p>Telefon: 0152 – 531 56 569</p>
                <p>Sofern Sie der Erhebung, Verarbeitung oder Nutzung Ihrer Daten durch uns nach Maßgabe dieser Datenschutzbestimmungen insgesamt oder für einzelne Maßnahmen widersprechen wollen, können Sie Ihren Widerspruch an den Verantwortlichen richten. Sie können diese Datenschutzerklärung jederzeit speichern und ausdrucken.</p>
                <h4>2. Allgemeine Zwecke der Verarbeitung</h4>
                <p>Wir verwenden personenbezogene Daten zum Zweck des Betriebs der Website Welche Daten wir verwenden und warum</p>
                <h4>2.1 Hosting</h4>
                <p>Die von uns in Anspruch genommenen Hosting-Leistungen dienen der Zurverfügungstellung der folgenden Leistungen: Infrastruktur- und Plattformdienstleistungen, Rechenkapazität, Speicherplatz und Datenbankdienste, Sicherheitsleistungen sowie technische Wartungsleistungen, die wir zum Zweck des Betriebs der Website einsetzen. Hierbei verarbeiten wir, bzw. unser Hostinganbieter Bestandsdaten, Kontaktdaten, Inhaltsdaten, Vertragsdaten, Nutzungsdaten, Meta- und Kommunikationsdaten von Kunden, Interessenten und Besuchern dieser Website auf Grundlage unserer berechtigten Interessen an einer effizienten und sicheren Zurverfügungstellung unserer Website gem. Art. 6 Abs. 1 S. 1 f. DSGVO i.V.m. Art. 28 DSGVO.</p>
                <h4>2.2 Zugriffsdaten</h4>
                <p>Wir sammeln Informationen über Sie, wenn Sie diese Website nutzen. Wir erfassen automatisch Informationen über Ihr Nutzungsverhalten und Ihre Interaktion mit uns und registrieren Daten zu Ihrem Computer oder Mobilgerät. Wir erheben, speichern und nutzen Daten über jeden Zugriff auf unsere Website (sogenannte Serverlogfiles). Zu den Zugriffsdaten gehören:</p>
                <ul>
                    <li>Name und URL der abgerufenen Datei</li>
                    <li>Datum und Uhrzeit des Abrufs</li>
                    <li>übertragene Datenmenge</li>
                    <li>Meldung über erfolgreichen Abruf (HTTP response code)</li>
                    <li>Browsertyp und Browserversion</li>
                    <li>Betriebssystem</li>
                    <li>Referer URL (d.h. die zuvor besuchte Seite)</li>
                    <li>Websites, die vom System des Nutzers über unsere Website aufgerufen werden</li>
                    <li>Internet-Service-Provider des Nutzers</li>
                    <li>IP-Adresse und der anfragende Provider</li>
                </ul>
                <p>Wir nutzen diese Protokolldaten ohne Zuordnung zu Ihrer Person oder sonstiger Profilerstellung für statistische Auswertungen zum Zweck des Betriebs, der Sicherheit und der Optimierung unserer Website, aber auch zur anonymen Erfassung der Anzahl der Besucher auf unserer Website (traffic) sowie zum Umfang und zur Art der Nutzung unserer Website und Dienste, ebenso zu Abrechnungszwecken, um die Anzahl der von Kooperationspartnern erhaltenen Clicks zu messen. Aufgrund dieser Informationen können wir personalisierte und standortbezogene Inhalte zur Verfügung stellen und den Datenverkehr analysieren, Fehler suchen und beheben und unsere Dienste verbessern. Hierin liegt auch unser berechtigtes Interesse gemäß Art 6 Abs. 1 S. 1 f. DSGVO. Wir behalten uns vor, die Protokolldaten nachträglich zu überprüfen, wenn aufgrund konkreter Anhaltspunkte der berechtigte Verdacht einer rechtswidrigen Nutzung besteht. IP-Adressen speichern wir für einen begrenzten Zeitraum in den Logfiles, wenn dies für Sicherheitszwecke erforderlich oder für die Leistungserbringung oder die Abrechnung einer Leistung nötig ist, z. B. wenn Sie eines unserer Angebote nutzen. Nach Abbruch des Vorgangs der Bestellung oder nach Zahlungseingang löschen wir die IP-Adresse, wenn diese für Sicherheitszwecke nicht mehr erforderlich ist. IP-Adressen speichern wir auch dann, wenn wir den konkreten Verdacht einer Straftat im Zusammenhang mit der Nutzung unserer Website haben. Außerdem speichern wir als Teil Ihres Accounts das Datum Ihres letzten Besuchs (z.B. bei Registrierung, Login, Klicken von Links etc.).</p>
                <h4>2.3 Cookies</h4>
                <p>Wir verwenden sogenannte Session-Cookies, um unsere Website zu optimieren. Ein Session-Cookie ist eine kleine Textdatei, die von den jeweiligen Servern beim Besuch einer Internetseite verschickt und auf Ihrer Festplatte zwischengespeichert wird. Diese Datei als solche enthält eine sogenannte Session-ID, mit welcher sich verschiedene Anfragen Ihres Browsers der gemeinsamen Sitzung zuordnen lassen. Dadurch kann Ihr Rechner wiedererkannt werden, wenn Sie auf unsere Website zurückkehren. Diese Cookies werden gelöscht, nachdem Sie Ihren Browser schließen. Sie dienen z. B. dazu, dass Sie die Warenkorbfunktion über mehrere Seiten hinweg nutzen können. Wir verwenden in geringem Umfang auch persistente Cookies (ebenfalls kleine Textdateien, die auf Ihrem Endgerät abgelegt werden), die auf Ihrem Endgerät verbleiben und es uns ermöglichen, Ihren Browser beim nächsten Besuch wiederzuerkennen. Diese Cookies werden auf Ihrer Festplatte gespeichert und löschen sich nach der vorgegebenen Zeit von allein. Ihre Lebensdauer beträgt 1 Monat bis 10 Jahre. So können wir Ihnen unser Angebot nutzerfreundlicher, effektiver und sicherer präsentieren und Ihnen beispielsweise speziell auf Ihre Interessen abgestimmte Informationen auf der Seite anzeigen. Unser berechtigtes Interesse an der Nutzung der Cookies gemäß Art 6 Abs. 1 S. 1 f. DSGVO liegt darin, unsere Website nutzerfreundlicher, effektiver und sicherer zu machen. In den Cookies werden etwa folgende Daten und Informationen gespeichert:</p>
                <ul>
                    <li>Log-In-Informationen</li>
                    <li>Spracheinstellungen</li>
                    <li>eingegebene Suchbegriffe</li>
                    <li>Informationen über die Anzahl der Aufrufe unserer Website sowie Nutzung einzelner Funktionen unseres Internetauftritts</li>
                </ul>
                <p>Bei Aktivierung des Cookies wird diesem eine Identifikationsnummer zugewiesen und eine Zuordnung Ihrer personenbezogenen Daten zu dieser Identifikationsnummer wird nicht vorgenommen. Ihr Name, Ihre IP-Adresse oder ähnliche Daten, die eine Zuordnung des Cookies zu Ihnen ermöglichen würden, werden nicht in den Cookie eingelegt. Auf Basis der Cookie-Technologie erhalten wir lediglich pseudonymisierte Informationen, beispielsweise darüber, welche Seiten unseres Shops besucht wurden, welche Produkte angesehen wurden, etc. Sie können Ihren Browser so einstellen, dass Sie über das Setzen von Cookies vorab informiert werden und im Einzelfall entscheiden können, ob Sie die Annahme von Cookies für bestimmte Fälle oder generell ausschließen, oder dass Cookies komplett verhindert werden. Dadurch kann die Funktionalität der Website eingeschränkt werden.</p>
                <h4>2.4 Daten zur Erfüllung unserer vertraglichen Pflichten</h4>
                <p>Wir verarbeiten personenbezogene Daten, die wir zur Erfüllung unserer vertraglichen Pflichten benötigen, etwa Name, Adresse, E-Mail-Adresse, bestellte Produkte, Rechnungs- und Zahlungsdaten. Die Erhebung dieser Daten ist für den Vertragsschluss erforderlich. Die Löschung der Daten erfolgt nach Ablauf der Gewährleistungsfristen und gesetzlicher Aufbewahrungsfristen. Daten, die mit einem Nutzerkonto verknüpft sind (siehe unten), bleiben in jedem Fall für die Zeit der Führung dieses Kontos erhalten. Die Rechtgrundlage für die Verarbeitung dieser Daten ist Art. 6 Abs. 1 S. 1 b DSGVO, denn diese Daten werden benötigt, damit wir unsere vertraglichen Pflichten Ihnen gegenüber erfüllen können.</p>
                <h4>2.5 Nutzerkonto</h4>
               <p>Sie können auf unserer Website ein Nutzerkonto anlegen. Wünschen Sie dies, so benötigen wir die beim Login abgefragten personenbezogenen Daten. Beim späteren Einloggen werden nur Ihre Email bzw. Benutzername und das von Ihnen gewählte Passwort benötigt. Für die Neuregistrierung erheben wir Stammdaten (z. B. Name, Adresse), Kommunikationsdaten (z. B. E-Mail-Adresse) und Zahlungsdaten (Bankverbindung) sowie Zugangsdaten (Benutzername u. Passwort). Um Ihre ordnungsgemäße Anmeldung sicherzustellen und unautorisierte Anmeldungen durch Dritte zu verhindern, erhalten Sie nach Ihrer Registrierung einen Aktivierungslink per E-Mail, um Ihren Account zu aktivieren. Erst nach erfolgter Registrierung speichern wir die von Ihnen übermittelten Daten dauerhaft in unserem System. Sie können ein einmal angelegtes Nutzerkonto jederzeit von uns löschen lassen, ohne dass hierfür andere als die Übermittlungskosten nach den Basistarifen entstehen. Eine Mitteilung in Textform an die unter Ziffer 1 genannten Kontaktdaten (z.B. E-Mail, Fax, Brief) reicht hierfür aus. Wir werden dann Ihre gespeicherten personenbezogenen Daten löschen, soweit wir diese nicht noch zur Abwicklung von Bestellungen oder aufgrund gesetzlicher Aufbewahrungspflichten speichern müssen. Rechtgrundlage für die Verarbeitung dieser Daten ist Ihre Einwilligung gemäß Art. 6 Abs. 1 S. 1 a DSGVO.</p>
               <h4>2.6 Newsletter</h4>
               <p>Zur Anmeldung für den Newsletter werden die im Anmeldeprozess abgefragten Daten benötigt. Die Anmeldung zum Newsletter wird protokolliert. Nach der Anmeldung erhalten sie auf die angegebene Emailadresse eine Nachricht, in der Sie um die Bestätigung der Anmeldung gebeten werden („Double Opt-in“). Das ist notwendig, damit sich nicht Dritte mit ihrer Emailadresse anmelden können. Sie können jederzeit Ihre Einwilligung zum Empfang des Newsletters widerrufen und somit den Newsletter abbestellen. Wir speichern die Anmeldedaten solange diese für den Versand des Newsletters benötigt werden. Die Protokollierung der Anmeldung und die Versandadresse speichern wir, solange ein Interesse am Nachweis der ursprünglich gegebenen Einwilligung bestand, in der Regel sind das die Verjährungsfristen für zivilrechtliche Ansprüche, mithin maximal drei Jahre. Rechtsgrundlage für den Versand des Newsletters ist Ihre Einwilligung gem. Art. 6 Abs. 1 S. 1 a iVm Art. 7 DSGVO iVm § 7 Abs. 2 Nr. 3 UWG. Rechtsgrundlage für die Protokollierung der Anmeldung ist unser berechtigtes Interesse am Nachweis, dass der Versand mit Ihrer Einwilligung vorgenommen wurde. Sie können die Anmeldung jederzeit rückgängig machen, ohne dass hierfür andere als die Übermittlungskosten nach den Basistarifen entstehen. Eine Mitteilung in Textform an die unter Ziffer 1 genannten Kontaktdaten (z.B. E-Mail, Fax, Brief) reicht hierfür aus. Selbstverständlich finden Sie auch in jedem Newsletter einen Abmelde-Link.</p>
               <h4>2.7 Produktempfehlungen</h4>
               <p>Wir senden Ihnen unabhängig vom Newsletter regelmäßig Produktempfehlungen per E-Mail zu. Auf diese Weise lassen wir Ihnen Informationen über Produkte aus unserem Angebot zukommen, für die Sie sich auf Grundlage Ihrer letzten Käufe von Waren oder Dienstleistungen bei uns interessieren könnten. Dabei richten wir uns streng nach den gesetzlichen Vorgaben. Dem können Sie jederzeit widersprechen, ohne dass hierfür andere als die Übermittlungskosten nach den Basistarifen entstehen. Eine Mitteilung in Textform an die unter Ziffer 1 genannten Kontaktdaten (z.B. E-Mail, Fax, Brief) reicht hierfür aus. Selbstverständlich finden Sie auch in jeder E-Mail einen Abmelde-Link. Rechtsgrundlage hierfür ist die gesetzliche Erlaubnis nach Art. 6 Abs. 1 S. 1 f DSGVO iVm § 7 Abs. 3 UWG.</p>
               <h4>2.8 E-Mail Kontakt</h4>
               <p>Wenn Sie mit uns in Kontakt treten (z. B. per Kontaktformular oder E-Mail), verarbeiten wir Ihre Angaben zur Bearbeitung der Anfrage sowie für den Fall, dass Anschlussfragen entstehen. Erfolgt die Datenverarbeitung zur Durchführung vorvertraglicher Maßnahmen, die auf Ihre Anfrage hin erfolgen, bzw., wenn Sie bereits unser Kunde sind, zur Durchführung des Vertrages, ist Rechtsgrundlage für diese Datenverarbeitung Art. 6 Abs. 1 S. 1 b DSGVO. Weitere personenbezogene Daten verarbeiten wir nur, wenn Sie dazu einwilligen (Art. 6 Abs. 1 S. 1 a) DSGVO oder wir ein berechtigtes Interesse an der Verarbeitung Ihrer Daten haben (Art. 6 Abs. 1 S. 1 f) DSGVO. Ein berechtigtes Interesse liegt z. B. darin, auf Ihre E-Mail zu antworten.</p>
               <h4>3. Google Analytics</h4>
               <p>Wir benutzen Google Analytics, einen Webanalysedienst der Google Inc. („Google“). Google Analytics verwendet sog. „Cookies“, Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Website durch Sie ermöglichen. Die durch den Cookie erzeugten Informationen über Benutzung dieser Website durch die Seitenbesucher werden in der Regel an einen Server von Google in den USA übertragen und dort gespeichert. Hierin liegt auch unser berechtigtes Interesse gemäß Art 6 Abs. 1 S. 1 f DSGVO. Google hat sich dem zwischen der Europäischen Union und den USA geschlossenen Privacy-Shield-Abkommen unterworfen und sich zertifiziert. Dadurch verpflichtet sich Google, die Standards und Vorschriften des europäischen Datenschutzrechts einzuhalten. Nähere Informationen können Sie dem nachfolgend verlinkten Eintrag entnehmen: https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI&status=Active. Wir haben die IP-Anonymisierung auf dieser Website aktiviert (anonymizeIp). Dadurch wird Ihre IP-Adresse von Google jedoch innerhalb von Mitgliedstaaten der Europäischen Union oder in anderen Vertragsstaaten des Abkommens über den Europäischen Wirtschaftsraum zuvor gekürzt. Nur in Ausnahmefällen wird die volle IP-Adresse an einen Server von Google in den USA übertragen und dort gekürzt. In unserem Auftrag wird Google diese Informationen benutzen, um die Nutzung der Website durch Sie auszuwerten, um Reports über die Websiteaktivitäten zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen uns gegenüber zu erbringen. Die im Rahmen von Google Analytics von Ihrem Browser übermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengeführt. Sie können die Speicherung der Cookies durch eine entsprechende Einstellung Ihrer Browser-Software verhindern; wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Website vollumfänglich werden nutzen können. Sie können darüber hinaus die Übertragung der durch das Cookie erzeugten und auf Ihre Nutzung der Website bezogenen Daten (inkl. Ihrer IP-Adresse) an Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem Sie das unter dem folgenden Link verfügbare Browser-Plugin herunterladen und installieren: http://tools.google.com/dlpage/gaoptout?hl=de. Alternativ zum Browser-Plugin oder innerhalb von Browsern auf mobilen Geräten können Sie auf den folgenden Link klicken, um ein Opt-Out-Cookie zu setzen, der die Erfassung durch Google Analytics innerhalb dieser Website zukünftig verhindert (dieses Opt-Out-Cookie funktioniert nur in diesem Browser und nur für diese Domain. Löschen Sie die Cookies in Ihrem Browser, müssen Sie diesen Link erneut klicken): [Google Analytics deaktivieren] Hinweis für den Verantwortlichen (gehört nicht in die Datenschutzerklärung!):</p>
               <p>Das von Google angebotene Browser-Plugin zum Deaktivieren des Cookies funktioniert nicht auf mobilen Endgeräten. Aber auch dort muss der Betroffene die Möglichkeit haben, die Erfassung seiner IP-Adresse zu verhindern. Daher muss ein spezielles Javascript eingebunden werden mit folgendem Code (wobei die „xxxxxxx“ für die Analytics ID stehen):</p>
               <p>Der Link wird dann in der Datenschutzerklärung an der gelb markierten Stelle wie folgt eingebunden (wobei der Link-Text zwischen den  und  frei wählbar ist:</p>
               <p>Google Analytics deaktivieren</p>
               <p>Die anonymizeIP-Funktion wird um die Zeile ga("set", "anonymizeIp", true); ergänzt, etwa wie folgt:</p>
               <h4>4. Speicherdauer</h4>
               <p>Sofern nicht spezifisch angegeben speichern wir personenbezogene Daten nur so lange, wie dies zur Erfüllung der verfolgten Zwecke notwendig ist. In einigen Fällen sieht der Gesetzgeber die Aufbewahrung von personenbezogenen Daten vor, etwa im Steuer- oder Handelsrecht. In diesen Fällen werden die Daten von uns lediglich für diese gesetzlichen Zwecke weiter gespeichert, aber nicht anderweitig verarbeitet und nach Ablauf der gesetzlichen Aufbewahrungsfrist gelöscht.</p>
               <h4>5. Ihre Rechte als von der Datenverarbeitung Betroffener</h4>
               <p>Nach den anwendbaren Gesetzen haben Sie verschiedene Rechte bezüglich Ihrer personenbezogenen Daten. Möchten Sie diese Rechte geltend machen, so richten Sie Ihre Anfrage bitte per E-Mail oder per Post unter eindeutiger Identifizierung Ihrer Person an die in Ziffer 1 genannte Adresse. Nachfolgend finden Sie eine Übersicht über Ihre Rechte.</p>
               <h4>5.1 Recht auf Bestätigung und Auskunft</h4>
               <p>Sie haben das Recht auf eine übersichtliche Auskunft über die Verarbeitung Ihrer personenbezogenen Daten. Im Einzelnen: Sie haben jederzeit das Recht, von uns eine Bestätigung darüber zu erhalten, ob Sie betreffende personenbezogene Daten verarbeitet werden. Ist dies der Fall, so haben Sie das Recht, von uns eine unentgeltliche Auskunft über die zu Ihnen gespeicherten personenbezogenen Daten nebst einer Kopie dieser Daten zu verlangen. Des Weiteren besteht ein Recht auf folgende Informationen:</p>
               <p>1. die Verarbeitungszwecke;</p>
               <p>2. die Kategorien personenbezogener Daten, die verarbeitet werden;</p>
               <p>3. die Empfänger oder Kategorien von Empfängern, gegenüber denen die personenbezogenen Daten offengelegt worden sind oder noch offengelegt werden, insbesondere bei Empfängern in Drittländern oder bei internationalen Organisationen;</p>
               <p>4. falls möglich, die geplante Dauer, für die die personenbezogenen Daten gespeichert werden, oder, falls dies nicht möglich ist, die Kriterien für die Festlegung dieser Dauer;</p>
               <p>5. das Bestehen eines Rechts auf Berichtigung oder Löschung der Sie betreffenden personenbezogenen Daten oder auf Einschränkung der Verarbeitung durch den Verantwortlichen oder eines Widerspruchsrechts gegen diese Verarbeitung;</p>
               <p>6. das Bestehen eines Beschwerderechts bei einer Aufsichtsbehörde;</p>
               <p>7. wenn die personenbezogenen Daten nicht bei Ihnen erhoben werden, alle verfügbaren Informationen über die Herkunft der Daten;</p>
               <p>8. das Bestehen einer automatisierten Entscheidungsfindung einschließlich Profiling gemäß Art. 22 Abs. 1 und 4 DSGVO und – zumindest in diesen Fällen – aussagekräftige Informationen über die involvierte Logik sowie die Tragweite und die angestrebten Auswirkungen einer derartigen Verarbeitung für Sie.</p>
               <p>Werden personenbezogene Daten an ein Drittland oder an eine internationale Organisation übermittelt, so haben Sie das Recht, über die geeigneten Garantien gemäß Art. 46 DSGVO im Zusammenhang mit der Übermittlung unterrichtet zu werden.</p>
               <h4>5.2 Recht auf Berichtigung</h4>
               <p>Sie haben das Recht, von uns die Berichtigung und ggf. auch Vervollständigung Sie betreffender personenbezogener Daten zu verlangen.</p>
               <p>Im Einzelnen:</p>
               <p>Sie haben das Recht, von uns unverzüglich die Berichtigung Sie betreffender unrichtiger personenbezogener Daten zu verlangen. Unter Berücksichtigung der Zwecke der Verarbeitung haben Sie das Recht, die Vervollständigung unvollständiger personenbezogener Daten – auch mittels einer ergänzenden Erklärung – zu verlangen.</p>
               <h4>5.3 Recht auf Löschung („Recht auf Vergessenwerden“)</h4>
               <p>In einer Reihe von Fällen sind wir verpflichtet, Sie betreffende personenbezogene Daten zu löschen.</p>
               <p>Im Einzelnen:</p>
               <p>Sie haben gemäß Art. 17 Abs. 1 DSGVO das Recht, von uns zu verlangen, dass Sie betreffende personenbezogene Daten unverzüglich gelöscht werden, und wir sind verpflichtet, personenbezogene Daten unverzüglich zu löschen, sofern einer der folgenden Gründe zutrifft:</p>
               <p>1. Die personenbezogenen Daten sind für die Zwecke, für die sie erhoben oder auf sonstige Weise verarbeitet wurden, nicht mehr notwendig.</p>
               <p>2. Sie widerrufen Ihre Einwilligung, auf die sich die Verarbeitung gemäß Art. 6 Abs. 1 S. 1 a) DSGVO oder Art. 9 Abs. 2 a DSGVO stützte, und es fehlt an einer anderweitigen Rechtsgrundlage für die Verarbeitung.</p>
               <p>3. Sie legen gemäß Art. 21 Abs. 1 DSGVO Widerspruch gegen die Verarbeitung ein und es liegen keine vorrangigen berechtigten Gründe für die Verarbeitung vor, oder Sie legen gemäß Art. 21 Abs. 2 DSGVO Widerspruch gegen die Verarbeitung ein.</p>
               <p>4. Die personenbezogenen Daten wurden unrechtmäßig verarbeitet.</p>
               <p>5. Die Löschung der personenbezogenen Daten ist zur Erfüllung einer rechtlichen Verpflichtung nach dem Unionsrecht oder dem Recht der Mitgliedstaaten erforderlich, dem wir unterliegen.</p>
               <p>6. Die personenbezogenen Daten wurden in Bezug auf angebotene Dienste der Informationsgesellschaft gemäß Art. 8 Abs. 1 DSGVO erhoben.</p>
               <p>Haben wir die personenbezogenen Daten öffentlich gemacht und sind wir gemäß Art. 17 Abs. 1 DSGVO zu deren Löschung verpflichtet, so treffen wir unter Berücksichtigung der verfügbaren Technologie und der Implementierungskosten angemessene Maßnahmen, auch technischer Art, um für die Datenverarbeitung Verantwortliche, die die personenbezogenen Daten verarbeiten, darüber zu informieren, dass Sie von ihnen die Löschung aller Links zu diesen personenbezogenen Daten oder von Kopien oder Replikationen dieser personenbezogenen Daten verlangt haben.</p>
               <h4>5.4 Recht auf Einschränkung der Verarbeitung</h4>
               <p>In einer Reihe von Fällen sind Sie berechtigt, von uns eine Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen.</p>
               <p>Im Einzelnen:</p>
               <p>Sie haben das Recht, von uns die Einschränkung der Verarbeitung zu verlangen, wenn eine der folgenden Voraussetzungen gegeben ist:</p>
               <p>1. die Richtigkeit der personenbezogenen Daten wird von Ihnen bestritten, und zwar für eine Dauer, die es uns ermöglicht, die Richtigkeit der personenbezogenen Daten zu überprüfen,</p>
               <p>2. die Verarbeitung unrechtmäßig ist und Sie die Löschung der personenbezogenen Daten ablehnten und stattdessen die Einschränkung der Nutzung der personenbezogenen Daten verlangt haben;</p>
               <p>3. wir die personenbezogenen Daten für die Zwecke der Verarbeitung nicht länger benötigen, Sie die Daten jedoch zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen benötigen, oder</p>
               <p>4. Sie Widerspruch gegen die Verarbeitung gemäß Art. 21 Abs. 1 DSGVO eingelegt haben, solange noch nicht feststeht, ob die berechtigten Gründe unseres Unternehmens gegenüber den Ihren überwiegen.</p>
               <h4>5.5 Recht auf Datenübertragbarkeit</h4>
               <p>Sie haben das Recht, Sie betreffende personenbezogene Daten maschinenlesbar zu erhalten, zu übermitteln, oder von uns übermitteln zu lasen.</p>
               <p>Im Einzelnen:</p>
               <p>Sie haben das Recht, die Sie betreffenden personenbezogenen Daten, die Sie uns bereitgestellt haben, in einem strukturierten, gängigen und maschinenlesbaren Format zu erhalten, und Sie haben das Recht, diese Daten einem anderen Verantwortlichen ohne Behinderung durch uns zu übermitteln, sofern</p>
               <p>1. die Verarbeitung auf einer Einwilligung gemäß Art. 6 Abs. 1 S. 1 a) DSGVO oder Art. 9 Abs. 2 a) DSGVO oder auf einem Vertrag gemäß Art. 6 Abs. 1 S. 1 b) DSGVO beruht und</p>
               <p>2. die Verarbeitung mithilfe automatisierter Verfahren erfolgt.</p>
               <p>Bei der Ausübung Ihres Rechts auf Datenübertragbarkeit gemäß Absatz 1 haben Sie das Recht, zu erwirken, dass die personenbezogenen Daten direkt von uns einem anderen Verantwortlichen übermittelt werden, soweit dies technisch machbar ist.</p>
               <h4>5.6 Widerspruchsrecht</h4>
               <p>Sie haben das Recht, aus einer rechtmäßigen Verarbeitung Ihrer personenbezogenen Daten durch uns zu widersprechen, wenn sich dies aus Ihrer besonderen Situation begründet und unsere Interessen an der Verarbeitung nicht überwiegen.</p>
               <p>Im Einzelnen:</p>
               <p>Sie haben das Recht, aus Gründen, die sich aus Ihrer besonderen Situation ergeben, jederzeit gegen die Verarbeitung Sie betreffender personenbezogener Daten, die aufgrund von Art. 6 Abs. 1 S. 1 e) oder f) DSGVO erfolgt, Widerspruch einzulegen; dies gilt auch für ein auf diese Bestimmungen gestütztes Profiling. Wir verarbeiten die personenbezogenen Daten nicht mehr, es sei denn, wir können zwingende schutzwürdige Gründe für die Verarbeitung nachweisen, die Ihre Interessen, Rechte und Freiheiten überwiegen, oder die Verarbeitung dient der Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen. Werden personenbezogene Daten von uns verarbeitet, um Direktwerbung zu betreiben, so haben Sie das Recht, jederzeit Widerspruch gegen die Verarbeitung Sie betreffender personenbezogener Daten zum Zwecke derartiger Werbung einzulegen; dies gilt auch für das Profiling, soweit es mit solcher Direktwerbung in Verbindung steht. Sie haben das Recht, aus Gründen, die sich aus Ihrer besonderen Situation ergeben, gegen die Sie betreffende Verarbeitung Sie betreffender personenbezogener Daten, die zu wissenschaftlichen oder historischen Forschungszwecken oder zu statistischen Zwecken gemäß Art. 89 Abs. 1 DSGVO erfolgt, Widerspruch einzulegen, es sei denn, die Verarbeitung ist zur Erfüllung einer im öffentlichen Interesse liegenden Aufgabe erforderlich.</p>
               <h4>5.7 Automatisierte Entscheidungen einschließlich Profiling</h4>
               <p>Sie haben das Recht, nicht einer ausschließlich auf einer automatisierten Verarbeitung – einschließlich Profiling – beruhenden Entscheidung unterworfen zu werden, die Ihnen gegenüber rechtliche Wirkung entfaltet oder Sie in ähnlicher Weise erheblich beeinträchtigt. Eine automatisierte Entscheidungsfindung auf der Grundlage der erhobenen personenbezogenen Daten findet nicht statt.</p>
               <h4>5.8 Recht auf Widerruf einer datenschutzrechtlichen Einwilligung</h4>
               <p>Sie haben das Recht, eine Einwilligung zur Verarbeitung personenbezogener Daten jederzeit zu widerrufen.</p>
               <h4>5.9 Recht auf Beschwerde bei einer Aufsichtsbehörde</h4>
               <p>Sie haben das Recht auf Beschwerde bei einer Aufsichtsbehörde, insbesondere in dem Mitgliedstaat Ihres Aufenthaltsorts, Ihres Arbeitsplatzes oder des Orts des mutmaßlichen Verstoßes, wenn Sie der Ansicht sind, dass die Verarbeitung der Sie betreffenden personenbezogenen Daten rechtswidrig ist.</p>
               <h4>6. Datensicherheit</h4>
               <p>Wir sind um die Sicherheit Ihrer Daten im Rahmen der geltenden Datenschutzgesetze und technischen Möglichkeiten maximal bemüht. Ihre persönlichen Daten werden bei uns verschlüsselt übertragen. Dies gilt für Ihre Bestellungen und auch für das Kundenlogin. Wir nutzen das Codierungssystem SSL (Secure Socket Layer), weisen jedoch darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich. Zur Sicherung Ihrer Daten unterhalten wir technische und organisatorische Sicherungsmaßnahmen entsprechend Art. 32 DSGVO, die wir immer wieder dem Stand der Technik anpassen. Wir gewährleisten außerdem nicht, dass unser Angebot zu bestimmten Zeiten zur Verfügung steht; Störungen, Unterbrechungen oder Ausfälle können nicht ausgeschlossen werden. Die von uns verwendeten Server werden regelmäßig sorgfältig gesichert.</p>
               <h4>7. Weitergabe von Daten an Dritte, keine Datenübertragung ins Nicht-EU-Ausland</h4>
               <p>Grundsätzlich verwenden wir Ihre personenbezogenen Daten nur innerhalb unseres Unternehmens. Wenn und soweit wir Dritte im Rahmen der Erfüllung von Verträgen einschalten (etwa Logistik-Dienstleister), erhalten diese personenbezogene Daten nur in dem Umfang, in welchem die Übermittlung für die entsprechende Leistung erforderlich ist. Für den Fall, dass wir bestimmte Teile der Datenverarbeitung auslagern („Auftragsverarbeitung“), verpflichten wir Auftragsverarbeiter vertraglich dazu, personenbezogene Daten nur im Einklang mit den Anforderungen der Datenschutzgesetze zu verwenden und den Schutz der Rechte der betroffenen Person zu gewährleisten. Eine Datenübertragung an Stellen oder Personen außerhalb der EU außerhalb des in dieser Erklärung in Ziffer 4 genannten Falls findet nicht statt und ist nicht geplant.</p>
               <h4>8. Datenschutzbeauftragter</h4>
               <p>Sollten Sie noch Fragen oder Bedenken zum Datenschutz haben, so wenden Sie sich bitte an unseren Datenschutzbeauftragten: René Brand</p>
               </div>
               <div className="containerThree">
                <h2>Allgemeine Geschäftsbedingungen</h2>
                <h4>(Online-Shop für Downloads) §1 Geltungsbereich und Anbieter:</h4>
                <p>(1) Diese Allgemeinen Geschäftsbedingungen gelten für alle Bestellungen, die Sie bei dem Online-Shop Bottel | Tattoo & Piercingstudio Ahaus bestellen bzw. herunterladen.</p>
                <p>(3) Unsere Lieferungen, Leistungen und Angebote erfolgen ausschließlich auf der Grundlage dieser Allgemeinen Geschäftsbedingungen. Die Allgemeinen Geschäftsbedingungen gelten gegenüber Unternehmen somit auch für alle künftigen Geschäftsbeziehungen, auch wenn sie nicht nochmals ausdrücklich vereinbart werden. Der Einbeziehung von Allgemeinen Geschäftsbedingungen eines Kunden, die unseren Allgemeinen Geschäftsbedingungen widersprechen, wird schon jetzt widersprochen.</p>
                <p>(4) Vertragssprache ist ausschließlich deutsch.</p>
                <p>(5) Sie können die derzeit gültigen Allgemeinen Geschäftsbedingungen auf der Website abrufen und ausdrucken.</p>
                <h4>§2 Vertragsschluss</h4>
                <p>(1) Die Warenpräsentation im Online-Shop stellt keinen verbindlichen Antrag auf den Abschluss eines Kaufvertrages dar. Vielmehr handelt es sich um eine unverbindliche Aufforderung, im Online-Shop Waren zu bestellen.</p>
                <p>(2) Mit Anklicken des Buttons „Jetzt zahlungspflichtig bestellen“ geben Sie ein verbindliches Kaufangebot ab (§ 145 BGB).</p>
                <p>(3) Erst durch Freischalten des Inhalts bzw. Bereitstellen eines Links kommt der Vertrag zustande.</p>
                <h4>§3 Preise</h4>
                <p>Die auf den Produktseiten genannten Preise enthalten die gesetzliche Mehrwertsteuer und sonstige Preisbestandteile und verstehen sich zzgl. der jeweiligen Versandkosten</p>
                <h4>§4 Zahlungsbedingungen; Verzug</h4>
                <p>(1) Die Zahlung erfolgt: Paypal, PayPal Express.</p>
                <p>(1) Sofern nicht anders vereinbart, erfolgt die Lieferung der Ware durch das Bereitstellen eines Links. Dieser kann von Ihnen betätigt werden und startet den Download auf das von Ihnen gewählte Speichermedium.</p>
                <p>(2) Es liegt im Verantwortungsbereich des Kunden, geeignete Software bereitzuhalten, die ein ordnungsgemäßes Öffnen, Bearbeiten und Ausdrucken der Dateien und Inhalte ermöglicht.</p>
                <h4>§7 Widerrufsbelehrung</h4>
                <p>Für den Fall, dass Sie Verbraucher im Sinne des § 13 BGB sind, also den Kauf zu Zwecken tätigen, die überwiegend weder ihrer gewerblichen noch ihrer selbständigen beruflichen Tätigkeit zugerechnet werden können, haben Sie ein Widerrufsrecht nach Maßgabe der folgenden Bestimmungen.</p>
                <h4>Widerrufsrecht</h4>
                <p>Sie haben das Recht, binnen vierzehn Tagen ohne Angabe von Gründen diesen Vertrag zu widerrufen. Die Widerrufsfrist beträgt vierzehn Tage ab dem Tag, an dem Sie oder ein von Ihnen benannter Dritter, der nicht der Beförderer ist, die Waren in Besitz genommen haben bzw. hat.</p>
                <p>Um Ihr Widerrufsrecht auszuüben, müssen Sie uns</p>
                <p>Firma: Bottel | Tattoo & Piercingstudio Ahaus</p>
                <p>Adresse: Lüderitzstrasse 1a, 48683 Ahaus</p>
                <p>E-Mail: mail@tattoo-piercing-profi.de</p>
                <p>Telefon: 02561-86 04 39</p>
                <p>mittels einer eindeutigen Erklärung (z. B. ein mit der Post versandter Brief, oder E-Mail) über Ihren Entschluss, diesen Vertrag zu widerrufen, informieren. Zur Wahrung der Widerrufsfrist reicht es aus, dass Sie die Mitteilung über die Ausübung des Widerrufsrechts vor Ablauf der Widerrufsfrist absenden.</p>
                <h4>Folgen des Widerrufs</h4>
                <p>Wenn Sie diesen Vertrag widerrufen, haben wir Ihnen alle Zahlungen, die wir von Ihnen erhalten haben, einschließlich der Lieferkosten (mit Ausnahme der zusätzlichen Kosten, die sich daraus ergeben, dass Sie eine andere Art der Lieferung als die von uns angebotene, günstigste Standardlieferung gewählt haben), unverzüglich und spätestens binnen vierzehn Tagen ab dem Tag zurückzuzahlen, an dem die Mitteilung über Ihren Widerruf dieses Vertrags bei uns eingegangen ist. Für diese Rückzahlung verwenden wir dasselbe Zahlungsmittel, das Sie bei der ursprünglichen Transaktion eingesetzt haben, es sei denn, mit Ihnen wurde ausdrücklich etwas anderes vereinbart; in keinem Fall werden Ihnen wegen dieser Rückzahlung Entgelte berechnet. Wir können die Rückzahlung verweigern, bis wir die Waren wieder zurückerhalten haben oder bis Sie den Nachweis erbracht haben, dass Sie die Waren zurückgesandt haben, je nachdem, welches der frühere Zeitpunkt ist. Sie haben die Waren unverzüglich und in jedem Fall spätestens binnen vierzehn Tagen ab dem Tag, an dem Sie uns über den Widerruf dieses Vertrags unterrichten, an uns oder an zurückzusenden oder zu übergeben. Die Frist ist gewahrt, wenn Sie die Waren vor Ablauf der Frist von vierzehn Tagen absenden. Sie tragen die unmittelbaren Kosten der Rücksendung der Waren. Sie müssen für einen etwaigen Wertverlust der Waren nur aufkommen, wenn dieser Wertverlust auf einen zur Prüfung der Beschaffenheit, Eigenschaften und Funktionsweise der Waren nicht notwendigen Umgang mit ihnen zurückzuführen ist.</p>
                <h4>Muster-Widerrufsformular</h4>
                <p>Wenn Sie den Vertrag widerrufen wollen, dann füllen Sie bitte dieses Formular aus und senden Sie es zurück.</p>
                <div className="formAGB">
                    <p>An</p>
                    <p>Firma: Bottel | Tattoo & Piercingstudio Ahaus</p>
                    <p>Adresse: Lüderitzstrasse 1a, 48683 Ahaus</p>
                    <p>E-Mail: mail@tattoo-piercing-profi.de</p>
                    <p>Telefon: 02561-86 04 39</p>
                    <p>Hiermit widerrufe(n) ich/wir (*) den von mir/uns (*) abgeschlossenen Vertrag über den Kauf der folgenden Waren (*):</p>
                    <p>Bestellt am (*)/erhalten am (*) Name des/der Verbraucher(s): Anschrift des/der Verbraucher(s):</p>
                    <p>Unterschrift des/der Verbraucher(s) (nur bei Mitteilung auf Papier)</p>
                    <p>Datum</p>
                    <p>(*) Unzutreffendes streichen.</p>
                </div>
                <h4>Ende der Widerrufsbelehrung</h4>
                <p>(1) Das Widerrufsrecht besteht nicht bei Lieferung von Waren, die nicht vorgefertigt sind und für deren Herstellung eine individuelle Auswahl oder Bestimmung durch den Verbraucher maßgeblich ist oder die eindeutig auf die persönlichen Bedürfnisse des Verbrauchers zugeschnitten sind oder bei Lieferung von Ton- oder Videoaufnahmen oder Computersoftware in einer versiegelten Packung, wenn die Versiegelung nach der Lieferung entfernt wurde.</p>
                <p>(2) Bitte vermeiden Sie Beschädigungen und Verunreinigungen. Senden Sie die Ware bitte möglichst in Originalverpackung mit sämtlichem Zubehör und mit allen Verpackungsbestandteilen an uns zurück. Verwenden Sie ggf. eine schützende Umverpackung. Wenn Sie die Originalverpackung nicht mehr besitzen, sorgen Sie bitte mit einer geeigneten Verpackung für einen ausreichenden Schutz vor Transportschäden, um Schadensersatzansprüche wegen Beschädigungen infolge mangelhafter Verpackung zu vermeiden.</p>
                <p>(3) Bitte rufen Sie vor Rücksendung unter der [Tel.Nr.] bei uns an, um die Rücksendung anzukündigen. Auf diese Weise ermöglichen Sie uns eine schnellstmögliche Zuordnung der Produkte.</p>
                <p>(4) Bitte beachten Sie, dass die in den vorstehenden Absätzen 2 und 3 genannten Modalitäten nicht Voraussetzung für die wirksame Ausübung des Widerrufsrechts sind.</p>
                <p>(5) Ein Widerrufsrecht erlischt gemäß § 356 Abs. 5 BGB bei einem Vertrag über die Lieferung von nicht auf einem körperlichen Datenträger befindlichen digitalen Inhalten, wenn der Unternehmer mit der Ausführung des Vertrags begonnen hat, nachdem der Verbraucher ausdrücklich zugestimmt hat, dass der Unternehmer mit der Ausführung des Vertrags vor Ablauf der Widerrufsfrist beginnt und seine Kenntnis davon bestätigt hat, dass er durch seine Zustimmung mit Beginn der Ausführung des Vertrags sein Widerrufsrecht verliert.</p>
                <h4>§9 Gewährleistung</h4>
                <p>(1) Soweit nicht ausdrücklich etwas anderes vereinbart ist, richten sich Ihre Gewährleistungsansprüche nach den gesetzlichen Bestimmungen des Kaufrechts (§§ 433 ff. BGB).</p>
                <p>(2) Wenn Sie Verbraucher im Sinne des § 13 BGB sind, beträgt die Verjährungsfrist für Gewährleistungsansprüche bei gebrauchten Sachen-abweichend von den gesetzlichen Bestimmungen – ein Jahr. Diese Beschränkung gilt nicht für Ansprüche aufgrund von Schäden aus der Verletzung des Lebens, des Körpers oder der Gesundheit oder aus der Verletzung einer wesentlichen Vertragspflicht, deren Erfüllung die ordnungsgemäße Durchführung des Vertrags überhaupt erst ermöglicht und auf deren Einhaltung der Vertragspartner regelmäßig vertrauen darf (Kardinalpflicht) sowie für Ansprüche aufgrund von sonstigen Schäden, die auf einer vorsätzlichen oder grob fahrlässigen Pflichtverletzung des Verwenders oder seiner Erfüllungsgehilfen beruhen.</p>
                <p>(3) Im Übrigen gelten für die Gewährleistung die gesetzlichen Bestimmungen.</p>
                <p>(4) Wenn Sie Unternehmer im Sinne des § 14 BGB sind, gelten die gesetzlichen Bestimmungen mit folgenden Modifikationen:</p>
                <p>– Für die Beschaffenheit der Ware sind nur unsere eigenen Angaben und die Produktbeschreibung des Herstellers verbindlich, nicht jedoch öffentliche Anpreisungen und Äußerungen und sonstige Werbung des Herstellers.</p>
                <p>– Sie sind verpflichtet, die Ware unverzüglich und mit der gebotenen Sorgfalt auf Qualitäts- und Mengenabweichungen zu untersuchen und uns offensichtliche Mängel binnen 7 Tagen ab Empfang der Ware anzuzeigen. Zur Fristwahrung reicht die rechtzeitige Absendung. Dies gilt auch für später festgestellte verdeckte Mängel ab Entdeckung. Bei Verletzung der Untersuchungs- und Rügepflicht ist die Geltendmachung der Gewährleistungsansprüche ausgeschlossen.</p>
                <p>– Bei Mängeln leisten wir nach unserer Wahl Gewähr durch Nachbesserung oder Ersatzlieferung (Nacherfüllung). Im Falle der Nachbesserung müssen wir nicht die erhöhten Kosten tragen, die durch die Verbringung der Ware an einen anderen Ort als den Erfüllungsort entstehen, sofern die Verbringung nicht dem bestimmungsgemäßen Gebrauch der Ware entspricht.</p>
                <p>– Schlägt die Nacherfüllung zweimal fehl, können Sie nach Ihrer Wahl Minderung verlangen oder vom Vertrag zurücktreten.</p>
                <p>– Die Gewährleistungsfrist beträgt ein Jahr ab Ablieferung der Ware.</p>
                <h4>§10 Haftung</h4>
                <p>(1) Unbeschränkte Haftung: Wir haften unbeschränkt für Vorsatz und grobe Fahrlässigkeit sowie nach Maßgabe des Produkthaftungsgesetzes. Für leichte Fahrlässigkeit haften wir bei Schäden aus der Verletzung des Lebens, des Körpers und der Gesundheit von Personen.</p>
                <p>(2) Im Übrigen gilt folgende beschränkte Haftung: Bei leichter Fahrlässigkeit haften wir nur im Falle der Verletzung einer wesentlichen Vertragspflicht, deren Erfüllung die ordnungsgemäße Durchführung des Vertrags überhaupt erst ermöglicht und auf deren Einhaltung Sie regelmäßig vertrauen dürfen (Kardinalpflicht). Die Haftung für leichte Fahrlässigkeit ist der Höhe nach beschränkt auf die bei Vertragsschluss vorhersehbaren Schäden, mit deren Entstehung typischerweise gerechnet werden muss. Diese Haftungsbeschränkung gilt auch zugunsten unserer Erfüllungsgehilfen.</p>
                <h4>§11 Urheber- und Nutzungsrechte</h4>
                <p>(1) Alle durch den Verkäufer bereitgestellten digitalen Inhalte sind urheberrechtlich geschützt.</p>
                <p>(2) Der Kunde erwirbt ein zeitlich unbegrenztes, einfaches, nicht übertragbares Nutzungsrecht ausschließlich für den nicht kommerziellen Gebrauch. Dem Kunden werden keine Verwertungsrechte eingeräumt. Insbesondere darf er die erworbenen Titel – weder digital noch in gedruckter Form, vollständig oder auszugsweise – nicht verbreiten (§ 17 UrhG), öffentlich zugänglich machen (§ 19a UrhG) oder in anderer Form an Dritte weitergeben. Das Recht zur Vervielfältigung (§ 16 UrhG) ist auf Vervielfältigungshandlungen beschränkt, die ausschließlich dem eigenen Gebrauch dienen.</p>
                <p>(3) Die Einräumung der Nutzungsrechte durch den Verkäufer steht unter der aufschiebenden Bedingung der vollständigen Kaufpreiszahlung.</p>
                <p>(4) Der Nutzer ist nicht berechtigt, Urheberrechtsvermerke, Markenzeichen oder andere Rechtsvorbehalte von den Waren zu entfernen.</p>
                <p>(5) Der Verkäufer ist berechtigt, zum Download bereitgestellte digitale Inhalte mit sichtbaren und unsichtbaren Kennzeichnungen individuell zu personalisieren, um die Ermittlung und rechtliche Verfolgung des ursprünglichen Bestellers im Falle einer missbräuchlichen Nutzung zu ermöglichen.</p>
                <p>(6) Im Fall einer unberechtigten Nutzung der digitalen Inhalte durch den Käufer oder einen Dritten verpflichtet sich der Käufer zur Zahlung einer Vertragsstrafe in Höhe von 10.000,- Euro pro Verletzungshandlung.</p>
                <h4>§12 Schlussbestimmungen</h4>
                <p>(1) Sollten eine oder mehrere Bestimmungen dieser AGB unwirksam sein oder werden, wird dadurch die Wirksamkeit der anderen Bestimmungen im Übrigen nicht berührt.</p>
                <p>(2) Auf Verträge zwischen uns und Ihnen ist ausschließlich deutsches Recht anwendbar unter Ausschluss der Bestimmungen der United Nations Convention on Contracts for the International Sale of Goods (CISG, „UN- Kaufrecht“).</p>
                <p>(3) Sind Sie Kaufmann, juristische Person des öffentlichen Rechts oder öffentlich- rechtliches Sondervermögen, so ist Gerichtsstand für alle Streitigkeiten aus oder im Zusammenhang mit Verträgen zwischen uns und Ihnen.</p>
               </div>
            </div>
        </div>
    )
}

export default AGB